secrets:
  mariadb_password:
    file: ./mariadb_password.txt

services:
  npm:
    image: jc21/nginx-proxy-manager:${NPM_TAG}
    restart: unless-stopped
    secrets:
      - mariadb_password
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
      - ${ADMIN_PORT}:81
    volumes:
      - ${VOLUME_PATH}/data:/data
      - ${VOLUME_PATH}/etc/letsencrypt:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD_FILE: /run/secrets/mariadb_password
      DB_MYSQL_NAME: npm
    depends_on:
      - db

  db:
    image: mariadb:${MARIADB_TAG}
    restart: unless-stopped
    secrets:
      - mariadb_password
    volumes:
      - ${VOLUME_PATH}/var/lib/mysql:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password
      MARIADB_DATABASE: npm
      MARIADB_USER: npm